name: swiftaid_user
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  google_maps_flutter: ^2.2.5
  geolocator: ^10.1.0
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  pin_code_fields: ^8.0.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  path: ^1.9.1
  geocoding: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/swift_aid_logo.png
    - assets/lottie/onboarding1.json
    - assets/lottie/onboarding2.json
    - assets/lottie/dashboard1.json
    - assets/lottie/sos_button.json
